# -*- coding: utf-8 -*-
"""Flie_handling_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DUJBFFX6nFFaVL7GTwqCmUeX5RcfH9be
"""

# Task 1 -  craete a new text file and write a few lines of text into it.
with open("pankaj.txt","w") as file:
  file.write("pwskills have to update the course content\n")
  file.write("You have just take fame using the name of pandey sir")

# Task 2: Open and read the contents of the file you just created.
with open("pankaj.txt","r") as file:
  content = file.read()
  print(content)

# 1/ Task 3: Add additional text to the existing file without deleting the current content.
with open ("pankaj.txt","a") as file:
  file.write("\nThis is the third line\n ")
  file.write("This is the fourth line")

#  Task 4: Read and print each line from the file one by one.
with open("pankaj.txt","r") as f:
  for line in f:
    print(line)

# Task 5: write the contents of a list to a file; with each item on a new line.
items=["Apple","Banana","Grapes","Anjir"]
with open("paw.txt","w") as file:
  for item in items:
    file.write(item+'\n')

#Task 6: Read the file content into a list, where e#ch line is an element of the list.
with open("pankaj.txt","r") as file:
  lines = file.readlines()
  print(lines)

#  Task 7: Count the total number of words in the file.
with open("paw.txt","r") as f:
  content=f.read()
  words=content.split()
  total_words=len(words)
  print(total_words)

# Task 8: Copy the contents of one file to another file
  import shutil
  shutil.copyfile("pankaj.txt","paw.txt")

# Task 9: Check the file before attempting to read it.
import os
if os.path.exists("pankaj.txt"):
  with open("pankaj.txt","r") as file:
    content=file.read()
    print(content)

# Delete a file using python
import os
if os.path.exists("paw.txt"):
  os.remove("paw.txt")
  print("file deleted")